# Generated by Django 3.1.2 on 2020-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('ru1', models.CharField(blank=True, max_length=128)),
                ('ru2', models.CharField(blank=True, max_length=128)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1')])),
                ('picture', models.CharField(blank=True, max_length=128)),
                ('audio', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
