# Generated by Django 3.1.2 on 2020-10-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.level'),
        ),
    ]
