# Generated by Django 3.1.2 on 2020-10-28 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0003_auto_20201028_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField()),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.uservocabulary')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='word',
            field=models.ManyToManyField(through='vocabulary.WordVocabulary', to='vocabulary.Word'),
        ),
    ]
