# Generated by Django 3.1.2 on 2020-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_auto_20201028_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordvocabulary',
            name='stage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
