# Generated by Django 3.1.2 on 2020-10-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_auto_20201028_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordvocabulary',
            options={'verbose_name_plural': 'WordVocabularies'},
        ),
    ]
