# Generated by Django 3.1.2 on 2020-10-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_auto_20201028_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservocabulary',
            options={'verbose_name_plural': 'UserVocabularies'},
        ),
        migrations.AlterModelOptions(
            name='wordvocabulary',
            options={},
        ),
    ]
