# Generated by Django 3.1.2 on 2020-10-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_auto_20201028_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordvocabulary',
            unique_together={('vocabulary', 'word')},
        ),
    ]
