# Generated by Django 3.1.2 on 2020-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_auto_20201029_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='picture',
            field=models.CharField(default='__blank__.jpg', max_length=128),
        ),
    ]
