# Generated by Django 3.1.2 on 2020-10-30 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabulary', '0009_uservocabulary_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('picture', models.CharField(default='__blank__.jpg', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserVocabularies',
            },
        ),
        migrations.CreateModel(
            name='WordWordset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordset', models.IntegerField(blank=True)),
                ('stage', models.PositiveIntegerField(default=0)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.userwordset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wordvocabulary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wordvocabulary',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='wordvocabulary',
            name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='eng',
        ),
        migrations.DeleteModel(
            name='UserVocabulary',
        ),
        migrations.DeleteModel(
            name='WordVocabulary',
        ),
        migrations.AddField(
            model_name='wordwordset',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word'),
        ),
        migrations.AddField(
            model_name='userwordset',
            name='words',
            field=models.ManyToManyField(through='vocabulary.WordWordset', to='vocabulary.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='wordwordset',
            unique_together={('wordset', 'word')},
        ),
    ]
