# Generated by Django 3.1.2 on 2020-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_auto_20201030_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordwordset',
            name='temporary',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
