# Generated by Django 3.1.2 on 2020-10-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0011_wordwordset_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordwordset',
            name='temporary',
        ),
        migrations.RemoveField(
            model_name='wordwordset',
            name='vocabulary',
        ),
        migrations.AlterField(
            model_name='wordwordset',
            name='wordset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.userwordset'),
        ),
    ]
